[package]
name = "flow-like-types"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
async-stream = "0.3.6"
async-trait = "0.1.88"
bytes = "1.10.1"
cuid2 = {version="0.1.4", default-features = false}
prost = "0.14.1"
prost-types = "0.14.1"
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["stream", "json", "gzip", "brotli", "socks", "http2", "default-tls", "rustls-tls"] }
schemars.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
dashmap = { version="6.1.0", features = ["serde", "rayon", "inline"] }
futures.workspace = true
image.workspace = true
imageproc.workspace = true
webp.workspace = true
base64.workspace=true
mime_guess = "2.0.5"
reqwest-eventsource = "0.6.0"
minijinja = "2.9.0"
rxing = { version = "0.7.1", features = ["serde", "image"] }
ab_glyph = "0.2.29"
tokio-util = "0.7.15"
jsonschema = "0.33.0"
regex.workspace = true

[build-dependencies]
prost-build = "0.13.5"
