[project]
name = "model-evaluator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.2.2",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "rapidfuzz>=3.14.3",
    "requests>=2.32.5",
]
