name: "FOSSA License Test"

on:
  pull_request:
    branches:
      - dev

jobs:
  fossa-test:
    name: FOSSA Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Skip for fork PRs where secrets aren't available
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run FOSSA Test
        uses: fossas/fossa-action@c414b9ad82eaad041e47a7cf62a4f02411f427a0 # v1.8.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true